using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace PT_2_MML
{
	/// <summary>
	/// Contains information about autogenerated macros
	/// </summary>
	public class Macro
	{
		/// <summary>
		/// For a volume slide, the initial value
		/// </summary>
		public int BaseVolume;

		/// <summary>
		/// For a volume slide, the amount per tick
		/// </summary>
		public int VolumeSlide;

		/// <summary>
		/// The ID of this macro
		/// </summary>
		public int ID;
	}
}
